panda_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
  gains:
    panda_joint1: {p: 15000, d: 50, i: 0.01, i_clamp: 1}
    panda_joint2: {p: 15000, d: 50, i: 0.01, i_clamp: 1}
    panda_joint3: {p: 15000, d: 50, i: 0.01, i_clamp: 1}
    panda_joint4: {p: 15000, d: 50, i: 0.01, i_clamp: 1}
    panda_joint5: {p: 15000, d: 50, i: 0.01, i_clamp: 1}
    panda_joint6: {p: 5000, d: 50, i: 0.01, i_clamp: 1}
    panda_joint7: {p: 2000, d: 50, i: 0.01, i_clamp: 1}

  state_publish_rate: 25
  constraints:
    goal_time: 2.0

panda_hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - panda_finger_joint1
    - panda_finger_joint2
  gains:
        panda_finger_joint1: { p: 5, d: 1.0, i: 0 }
        panda_finger_joint2: { p: 5, d: 1.0, i: 0 }

  state_publish_rate: 25
